# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: adal-bos <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/07/07 21:41:40 by adal-bos          #+#    #+#              #
#    Updated: 2024/07/07 21:41:57 by adal-bos         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


NAME=ft_display_file
SRCS=srcs/*.c

all:
	gcc $(SRCS) -o $(NAME)

clean:
	/bin/rm -f *.o

fclean: clean
	/bin/rm -f $(NAME)

re: fclean re
